name: 'Checkout'
description: 'Checkout a Git repository'
inputs: 
  repository:
    description: 'Repository name'
    default: ${{ github.repository }}
  ref:
    description: >
      Ref to checkout (SHA, branch, tag). For the repository that triggered the
      workflow, defaults to the ref/SHA for the event. Otherwise defaults to master.
  token:
    description: 'Access token for clone repository'
    default: ${{ github.token }}
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
  clean:
    description: 'Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching'
    default: true
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history.'
    default: 1
  lfs:
    description: 'Whether to download Git-LFS files'
    default: false
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js